name: Issue Comment draft

# Controls when the workflow will run
on:
  issue_comment:

jobs:
  comment:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: ./.github/actions/comment-issue
        if: contains(github.event.comment.body, '/preparation')
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment: "Hello world"
          
      # - uses: actions/github-script@v6
      #   if: contains(github.event.comment.body, '/preparation')
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       github.rest.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: "Hi, I'm preparing"
      #       })
