name: Issue Comment draft

# Controls when the workflow will run
on:
  issue_comment:

jobs:
  comment:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4 # needed to access local action
      - uses: ./.github/actions/comment-issue
        if: contains(github.event.comment.body, '/preparation')
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment: |
            ### Preparation checklist
            
            This checklist is for the preparation phase, skip it when not relevant.

            - [ ] if project contains CI pipeline, add \`Pipeline\` label
            - [ ] clean up repositories
            - [ ] pass file size limit check
            - [ ] convert binaries to LFS. (If applicable)
            - [ ] translate pipeline to GitHub Actions. (If applicable)
            - [ ] create users on AD
            - [ ] create team / AD group
